# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PhotoRetoucher' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'GPUImage', :git => 'https://github.com/sysu-huangwei/GPUImage.git', :branch => 'master'
#  pod 'GPUImage', :path => '../../GPUImage'

end
